name = "ispinfo-frontend-worker"
main = "_worker.js"
compatibility_date = "2024-07-01"

# For Cloudflare Pages
[site]
bucket = "./dist"

# For local development with wrangler dev
[build]
command = "npm run build"

# For production deployment
[env.production]
name = "ispinfo-frontend-worker-production"
compatibility_date = "2024-07-01"

# For preview deployments
[env.preview]
name = "ispinfo-frontend-worker-preview"
route = "preview.ispinfo.pages.dev/*"
