name = "ispinfo-backend"
main = "src/index.ts"
compatibility_date = "2024-03-25"

[build]
  command = "npm run build"
  cwd = "."

[dev]
  port = 8787
  ip = "127.0.0.1"
  local_protocol = "http"
  env = "development"

# Development environment variables (used with `wrangler dev`)
[vars]
  NODE_ENV = "development"
  ENVIRONMENT = "development"
  TURNSTILE_SECRET_KEY = "1x0000000000000000000000000000000AA"  # Test secret key for local development

# Production environment (used with `wrangler publish`)
[env.production]
  # These should be set in the Cloudflare Workers dashboard using:
  # wrangler secret put TURNSTILE_SECRET_KEY
  # wrangler secret put IPREGISTRY_API_KEY

# Uncomment and configure if you need to use KV namespaces
# [[kv_namespaces]]
#   binding = "MY_KV_NAMESPACE"
#   id = "..."
#   preview_id = "..."
