name: Deploy Backend to Cloudflare Workers (Simplified)

on:
  push:
    branches: [production]

jobs:
  deploy-backend:
    name: Deploy Backend (Production)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci
        working-directory: ./backend

      - name: Build
        run: npm run build
        working-directory: ./backend

      - name: List build artifacts
        run: ls -R backend/dist || echo "dist directory not found."

      - name: Deploy to Cloudflare Workers (Production)
        uses: cloudflare/wrangler-action@3.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: publish --env production --verbose
          workingDirectory: 'backend'
