name: Deploy Backend to Cloudflare Workers

on:
  push:
    branches: [main, production, staging]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  pull_request:
    branches: [main, production, staging]
    paths:
      - 'backend/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - production
          - staging

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    
    # 设置环境变量
    env:
      ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
      CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: ./backend

      - name: Build
        run: npm run build
        working-directory: ./backend

      - name: Configure Wrangler
        run: |
          npm install -g wrangler@latest
          wrangler --version
          wrangler whoami

      - name: Deploy to Cloudflare Workers (${{ env.ENVIRONMENT }})
        uses: cloudflare/wrangler-action@3.0.0
        with:
          apiToken: ${{ env.CF_API_TOKEN }}
          command: publish --env ${{ env.ENVIRONMENT }}
          workingDirectory: './backend'
        env:
          NODE_ENV: ${{ env.ENVIRONMENT }}
          CLOUDFLARE_ACCOUNT_ID: ${{ env.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ env.CF_API_TOKEN }}

      - name: Verify deployment
        run: |
          echo "Successfully deployed to ${{ env.ENVIRONMENT }} environment"
          echo "Deployment URL: https://${{ env.ENVIRONMENT == 'production' && 'api.ispinfo.io' || 'staging.api.ispinfo.io' }}"

      # 添加部署状态通知（可选，需要设置 SLACK_WEBHOOK_URL 密钥）
      - name: Notify deployment status
        if: always() && github.event_name != 'workflow_dispatch'  # 手动触发时不发送通知
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL || '' }}
          SLACK_TITLE: 'Backend Deployment ${{ job.status }} [${{ env.ENVIRONMENT }}]'
          SLACK_MESSAGE: >
            ${{ format('Repository: {0}\nBranch: {1}\nEvent: {2}\nStatus: {3}', 
                      github.repository,
                      github.ref_name,
                      github.event_name,
                      job.status == 'success' ? '✅ Succeeded' : '❌ Failed') }}
          SLACK_COLOR: ${{ job.status == 'success' && 'good' || 'danger' }}
          SLACK_USERNAME: GitHub Actions
          SLACK_ICON_EMOJI: ':github:'
